name: Fly Deploy

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create searxng.yml
        run: |
          cat > searxng.yml << EOF
          server:
            base_url: ${{ secrets.SEARXNG_BASE_URL }}
            secret_key: ${{ secrets.SEARXNG_SECRET_KEY }}

          EOF
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only